# Severity Levels
SEVERITY_HIGH = 'HIGH'
SEVERITY_MEDIUM = 'MEDIUM'
SEVERITY_LOW = 'LOW'

# Issue Types
ISSUE_TYPE_SECURITY = 'SECURITY'
ISSUE_TYPE_PERFORMANCE = 'PERFORMANCE'
ISSUE_TYPE_MAINTAINABILITY = 'MAINTAINABILITY'
ISSUE_TYPE_STYLE = 'STYLE'

# Score Weights
WEIGHT_SECURITY = 0.3
WEIGHT_COMPLEXITY = 0.25
WEIGHT_MAINTAINABILITY = 0.25
WEIGHT_STYLE = 0.2